/* GENERATED by validate/lvs/gen_blackboxes.py --- do not edit. */
/* Port-only stubs for every leaf of digital_top's structural view. */

/* housekeeping_top --- 49 pins, from verilog/rtl/housekeeping_top.v */
(* blackbox *)
module housekeeping_top (
    inout wire VPWR,
    inout wire VGND,
    input wire porb,
    input wire clk,
    input wire SCK,
    input wire SDI,
    input wire CSB,
    output wire SDO,
    output wire sdo_ena,
    output wire reset,
    output wire clk_out,
    input wire [31:0] mask_rev_in,
    output wire sram_clk,
    output wire [9:0] sram_addr,
    output wire [7:0] sram_idata,
    input wire [7:0] sram_odata,
    output wire sram_read,
    output wire sram_write,
    input wire [11:0] io_in,
    output wire [11:0] io_out,
    output wire [11:0] io_oe,
    output wire [23:0] dbus_out,
    input wire [11:0] dbus_in_left,
    input wire [11:0] dbus_in_right,
    output wire [4:0] proj_sel,
    output wire proj_ena,
    output wire proj_dig_ena,
    output wire proj_3v3_ena,
    output wire proj_1v2_ena,
    output wire [1:0] proj_ibias_ena,
    output wire proj_vbias_ena,
    output wire [3:0] analog_bus_ena,
    output wire [4:0] idac1_value,
    output wire [4:0] idac2_value,
    output wire [2:0] voltgen_ena,
    output wire voltgen_high,
    output wire [2:0] voltgen_value,
    output wire bandgap_ena,
    output wire [15:0] bandgap_trim,
    output wire biasgen_ena,
    output wire biasgen_coarse,
    output wire biasgen_fine,
    output wire biasgen_ref_vbg,
    output wire [2:0] bandgap_sink1,
    output wire [1:0] bandgap_sink2,
    output wire [2:0] voltgen_sink1,
    output wire [2:0] voltgen_sink2,
    output wire [4:0] voltgen_source,
    output wire project_zero
);
endmodule

/* user_project_control --- 24 pins, from verilog/rtl/user_project_control.v */
(* blackbox *)
module user_project_control (
    input wire [4:0] proj_addr,
    input wire [4:0] proj_sel,
    input wire clk,
    input wire dig_ena,
    input wire enable,
    input wire reset,
    input wire [3:0] analog_ena,
    input wire [1:0] ibias_ena,
    input wire vbias_ena,
    input wire power_3v3_ena,
    input wire power_1v2_ena,
    input wire [23:0] dig_in,
    input wire [11:0] dig_out_relay,
    output wire [11:0] dig_out,
    output wire proj_clk,
    output wire proj_ena,
    output wire proj_reset,
    output wire proj_3v3_ena,
    output wire proj_1v2_ena,
    output wire [3:0] proj_analog_ena,
    output wire [1:0] proj_ibias_ena,
    output wire proj_vbias_ena,
    output wire [23:0] proj_dig_in,
    input wire [11:0] proj_dig_out
);
endmodule

/* RM_IHPSG13_1P_1024x8_c2_bm_bist --- 17 pins, from ../ihp-sg13cmos5l/libs.ref/sg13cmos5l_sram/verilog/RM_IHPSG13_1P_1024x8_c2_bm_bist.v */
(* blackbox *)
module RM_IHPSG13_1P_1024x8_c2_bm_bist (
    input wire A_CLK,
    input wire A_MEN,
    input wire A_WEN,
    input wire A_REN,
    input wire [9:0] A_ADDR,
    input wire [7:0] A_DIN,
    input wire A_DLY,
    output wire [7:0] A_DOUT,
    input wire [7:0] A_BM,
    input wire A_BIST_CLK,
    input wire A_BIST_EN,
    input wire A_BIST_MEN,
    input wire A_BIST_WEN,
    input wire A_BIST_REN,
    input wire [9:0] A_BIST_ADDR,
    input wire [7:0] A_BIST_DIN,
    input wire [7:0] A_BIST_BM
);
endmodule

/* analog_switch_med --- 7 pins, from dependencies/sg13cmos5l_ocd_ip__analog_switches/verilog/analog_switch_med.v */
(* blackbox *)
module analog_switch_med (
    inout wire dvdd,
    inout wire dvss,
    inout wire avdd,
    inout wire avss,
    input wire enable,
    inout wire in,
    inout wire out
);
endmodule

/* analog_switch_small --- 7 pins, from dependencies/sg13cmos5l_ocd_ip__analog_switches/verilog/analog_switch_small.v */
(* blackbox *)
module analog_switch_small (
    inout wire dvdd,
    inout wire dvss,
    inout wire avdd,
    inout wire avss,
    input wire enable,
    inout wire in,
    inout wire out
);
endmodule

/* analog_pswitch_small --- 7 pins, from dependencies/sg13cmos5l_ocd_ip__analog_switches/verilog/analog_pswitch_small.v */
(* blackbox *)
module analog_pswitch_small (
    inout wire dvdd,
    inout wire dvss,
    inout wire avdd,
    inout wire avss,
    input wire enable,
    inout wire in,
    inout wire out
);
endmodule

/* power_stage1v2 --- 4 pins, from dependencies/sg13cmos5l_ocd_ip__analog_switches/verilog/power_stage1v2.v */
(* blackbox *)
module power_stage1v2 (
    inout wire DVSS,
    input wire enable,
    inout wire DVDD_IN,
    inout wire DVDD_OUT
);
endmodule

/* power_stage2 --- 6 pins, from dependencies/sg13cmos5l_ocd_ip__analog_switches/verilog/power_stage2.v */
(* blackbox *)
module power_stage2 (
    inout wire DVDD,
    inout wire DVSS,
    inout wire IOVSS,
    input wire enable,
    inout wire IOVDD_IN,
    inout wire IOVDD_OUT
);
endmodule

/* sg13cmos5l_ocd_ip__bandgap_v2 --- 9 pins, from dependencies/sg13cmos5l_ocd_ip__biasgen/verilog/sg13cmos5l_ocd_ip__bandgap_v2.v */
(* blackbox *)
module sg13cmos5l_ocd_ip__bandgap_v2 (
    inout wire dvdd,
    inout wire dvss,
    inout wire vdd,
    inout wire vss,
    input wire ena,
    input wire [15:0] trim,
    inout wire ibias1_250n,
    inout wire ibias2_1,
    inout wire vbg
);
endmodule

/* sg13cmos5l_ocd_ip__biasgen2 --- 24 pins, from dependencies/sg13cmos5l_ocd_ip__biasgen/verilog/sg13cmos5l_ocd_ip__biasgen2.v */
(* blackbox *)
module sg13cmos5l_ocd_ip__biasgen2 (
    inout wire dvdd,
    inout wire dvss,
    inout wire vdd,
    inout wire vss,
    input wire ena,
    input wire ref_sel_vbg,
    input wire ref_sel_coarse,
    input wire ref_sel_fine,
    input wire [2:0] bandgap_sink1,
    input wire [1:0] bandgap_sink2,
    input wire [2:0] voltgen_sink1,
    input wire [2:0] voltgen_sink2,
    input wire [4:0] voltgen_source,
    input wire [4:0] idac1_source,
    input wire [4:0] idac2_source,
    inout wire ref_in,
    inout wire vbg,
    inout wire bandgap_sink1_ibias,
    inout wire bandgap_sink2_ibias,
    inout wire voltgen_sink1_ibias,
    inout wire voltgen_sink2_ibias,
    inout wire voltgen_source_ibias,
    inout wire idac1_source_ibias,
    inout wire idac2_source_ibias
);
endmodule

/* sg13cmos5l_ocd_ip__voltgen_v2 --- 15 pins, from dependencies/sg13cmos5l_ocd_ip__biasgen/verilog/sg13cmos5l_ocd_ip__voltgen_v2.v */
(* blackbox *)
module sg13cmos5l_ocd_ip__voltgen_v2 (
    inout wire dvdd,
    inout wire dvss,
    inout wire vdd,
    inout wire vss,
    input wire ena,
    input wire ena1,
    input wire ena2,
    input wire high,
    input wire [2:0] s,
    inout wire ibias1u_1,
    inout wire ibias1u_2,
    inout wire ibias1u_3,
    inout wire vbg,
    inout wire vout1,
    inout wire vout2
);
endmodule

/* sg13cmos5l_ocd_ip__por --- 6 pins, from dependencies/sg13cmos5l_ocd_ip__por/verilog/sg13cmos5l_ocd_ip__por.v */
(* blackbox *)
module sg13cmos5l_ocd_ip__por (
    inout wire vdd1v2,
    inout wire vss,
    input wire ena,
    output wire por,
    output wire porb,
    output wire por_unbuf
);
endmodule

/* slot1_wrapper --- 18 pins, from verilog/rtl/slot1_wrapper.v */
(* blackbox *)
module slot1_wrapper (
    inout wire vdd_3v3,
    inout wire vdd_1v2,
    inout wire vss_3v3,
    inout wire vss_1v2,
    input wire enable,
    input wire clk,
    input wire reset,
    input wire [23:0] dig_in,
    output wire [11:0] dig_out,
    inout wire analog_pin0,
    inout wire analog_pin1,
    inout wire ibias0,
    inout wire ibias1,
    inout wire vbias,
    inout wire analog_bus0,
    inout wire analog_bus1,
    inout wire analog_bus2,
    inout wire analog_bus3
);
endmodule

/* slot2_wrapper --- 18 pins, from verilog/rtl/slot2_wrapper.v */
(* blackbox *)
module slot2_wrapper (
    inout wire vdd_3v3,
    inout wire vdd_1v2,
    inout wire vss_3v3,
    inout wire vss_1v2,
    input wire enable,
    input wire clk,
    input wire reset,
    input wire [23:0] dig_in,
    output wire [11:0] dig_out,
    inout wire analog_pin0,
    inout wire analog_pin1,
    inout wire ibias0,
    inout wire ibias1,
    inout wire vbias,
    inout wire analog_bus0,
    inout wire analog_bus1,
    inout wire analog_bus2,
    inout wire analog_bus3
);
endmodule

/* slot3_wrapper --- 18 pins, from verilog/rtl/slot3_wrapper.v */
(* blackbox *)
module slot3_wrapper (
    inout wire vdd_3v3,
    inout wire vdd_1v2,
    inout wire vss_3v3,
    inout wire vss_1v2,
    input wire enable,
    input wire clk,
    input wire reset,
    input wire [23:0] dig_in,
    output wire [11:0] dig_out,
    inout wire analog_pin0,
    inout wire analog_pin1,
    inout wire ibias0,
    inout wire ibias1,
    inout wire vbias,
    inout wire analog_bus0,
    inout wire analog_bus1,
    inout wire analog_bus2,
    inout wire analog_bus3
);
endmodule

/* slot4_wrapper --- 17 pins, from verilog/rtl/slot4_wrapper.v */
(* blackbox *)
module slot4_wrapper (
    inout wire vdd_3v3,
    inout wire vdd_1v2,
    inout wire vss_3v3,
    inout wire vss_1v2,
    input wire enable,
    input wire clk,
    input wire reset,
    input wire [23:0] dig_in,
    output wire [11:0] dig_out,
    inout wire analog_pin0,
    inout wire ibias0,
    inout wire ibias1,
    inout wire vbias,
    inout wire analog_bus0,
    inout wire analog_bus1,
    inout wire analog_bus2,
    inout wire analog_bus3
);
endmodule

/* slot5_wrapper --- 19 pins, from verilog/rtl/slot5_wrapper.v */
(* blackbox *)
module slot5_wrapper (
    inout wire vdd_3v3,
    inout wire vdd_1v2,
    inout wire vss_3v3,
    inout wire vss_1v2,
    input wire enable,
    input wire clk,
    input wire reset,
    input wire [23:0] dig_in,
    output wire [11:0] dig_out,
    inout wire analog_pin0,
    inout wire analog_pin1,
    inout wire analog_pin2,
    inout wire ibias0,
    inout wire ibias1,
    inout wire vbias,
    inout wire analog_bus0,
    inout wire analog_bus1,
    inout wire analog_bus2,
    inout wire analog_bus3
);
endmodule

/* slot6_wrapper --- 18 pins, from verilog/rtl/slot6_wrapper.v */
(* blackbox *)
module slot6_wrapper (
    inout wire vdd_3v3,
    inout wire vdd_1v2,
    inout wire vss_3v3,
    inout wire vss_1v2,
    input wire enable,
    input wire clk,
    input wire reset,
    input wire [23:0] dig_in,
    output wire [11:0] dig_out,
    inout wire analog_pin0,
    inout wire analog_pin1,
    inout wire ibias0,
    inout wire ibias1,
    inout wire vbias,
    inout wire analog_bus0,
    inout wire analog_bus1,
    inout wire analog_bus2,
    inout wire analog_bus3
);
endmodule

/* slot7_wrapper --- 18 pins, from verilog/rtl/slot7_wrapper.v */
(* blackbox *)
module slot7_wrapper (
    inout wire vdd_3v3,
    inout wire vdd_1v2,
    inout wire vss_3v3,
    inout wire vss_1v2,
    input wire enable,
    input wire clk,
    input wire reset,
    input wire [23:0] dig_in,
    output wire [11:0] dig_out,
    inout wire analog_pin0,
    inout wire analog_pin1,
    inout wire ibias0,
    inout wire ibias1,
    inout wire vbias,
    inout wire analog_bus0,
    inout wire analog_bus1,
    inout wire analog_bus2,
    inout wire analog_bus3
);
endmodule

/* slot8_wrapper --- 17 pins, from verilog/rtl/slot8_wrapper.v */
(* blackbox *)
module slot8_wrapper (
    inout wire vdd_3v3,
    inout wire vdd_1v2,
    inout wire vss_3v3,
    inout wire vss_1v2,
    input wire enable,
    input wire clk,
    input wire reset,
    input wire [23:0] dig_in,
    output wire [11:0] dig_out,
    inout wire analog_pin0,
    inout wire ibias0,
    inout wire ibias1,
    inout wire vbias,
    inout wire analog_bus0,
    inout wire analog_bus1,
    inout wire analog_bus2,
    inout wire analog_bus3
);
endmodule

/* slot9_wrapper --- 19 pins, from verilog/rtl/slot9_wrapper.v */
(* blackbox *)
module slot9_wrapper (
    inout wire vdd_3v3,
    inout wire vdd_1v2,
    inout wire vss_3v3,
    inout wire vss_1v2,
    input wire enable,
    input wire clk,
    input wire reset,
    input wire [23:0] dig_in,
    output wire [11:0] dig_out,
    inout wire analog_pin0,
    inout wire analog_pin1,
    inout wire analog_pin2,
    inout wire ibias0,
    inout wire ibias1,
    inout wire vbias,
    inout wire analog_bus0,
    inout wire analog_bus1,
    inout wire analog_bus2,
    inout wire analog_bus3
);
endmodule

/* slot10_wrapper --- 19 pins, from verilog/rtl/slot10_wrapper.v */
(* blackbox *)
module slot10_wrapper (
    inout wire vdd_3v3,
    inout wire vdd_1v2,
    inout wire vss_3v3,
    inout wire vss_1v2,
    input wire enable,
    input wire clk,
    input wire reset,
    input wire [23:0] dig_in,
    output wire [11:0] dig_out,
    inout wire analog_pin0,
    inout wire analog_pin1,
    inout wire analog_pin2,
    inout wire ibias0,
    inout wire ibias1,
    inout wire vbias,
    inout wire analog_bus0,
    inout wire analog_bus1,
    inout wire analog_bus2,
    inout wire analog_bus3
);
endmodule

/* slot11_wrapper --- 17 pins, from verilog/rtl/slot11_wrapper.v */
(* blackbox *)
module slot11_wrapper (
    inout wire vdd_3v3,
    inout wire vdd_1v2,
    inout wire vss_3v3,
    inout wire vss_1v2,
    input wire enable,
    input wire clk,
    input wire reset,
    input wire [23:0] dig_in,
    output wire [11:0] dig_out,
    inout wire analog_pin0,
    inout wire ibias0,
    inout wire ibias1,
    inout wire vbias,
    inout wire analog_bus0,
    inout wire analog_bus1,
    inout wire analog_bus2,
    inout wire analog_bus3
);
endmodule

/* slot12_wrapper --- 18 pins, from verilog/rtl/slot12_wrapper.v */
(* blackbox *)
module slot12_wrapper (
    inout wire vdd_3v3,
    inout wire vdd_1v2,
    inout wire vss_3v3,
    inout wire vss_1v2,
    input wire enable,
    input wire clk,
    input wire reset,
    input wire [23:0] dig_in,
    output wire [11:0] dig_out,
    inout wire analog_pin0,
    inout wire analog_pin1,
    inout wire ibias0,
    inout wire ibias1,
    inout wire vbias,
    inout wire analog_bus0,
    inout wire analog_bus1,
    inout wire analog_bus2,
    inout wire analog_bus3
);
endmodule

/* slot13_wrapper --- 18 pins, from verilog/rtl/slot13_wrapper.v */
(* blackbox *)
module slot13_wrapper (
    inout wire vdd_3v3,
    inout wire vdd_1v2,
    inout wire vss_3v3,
    inout wire vss_1v2,
    input wire enable,
    input wire clk,
    input wire reset,
    input wire [23:0] dig_in,
    output wire [11:0] dig_out,
    inout wire analog_pin0,
    inout wire analog_pin1,
    inout wire ibias0,
    inout wire ibias1,
    inout wire vbias,
    inout wire analog_bus0,
    inout wire analog_bus1,
    inout wire analog_bus2,
    inout wire analog_bus3
);
endmodule

/* slot14_wrapper --- 19 pins, from verilog/rtl/slot14_wrapper.v */
(* blackbox *)
module slot14_wrapper (
    inout wire vdd_3v3,
    inout wire vdd_1v2,
    inout wire vss_3v3,
    inout wire vss_1v2,
    input wire enable,
    input wire clk,
    input wire reset,
    input wire [23:0] dig_in,
    output wire [11:0] dig_out,
    inout wire analog_pin0,
    inout wire analog_pin1,
    inout wire analog_pin2,
    inout wire ibias0,
    inout wire ibias1,
    inout wire vbias,
    inout wire analog_bus0,
    inout wire analog_bus1,
    inout wire analog_bus2,
    inout wire analog_bus3
);
endmodule

/* slot15_wrapper --- 17 pins, from verilog/rtl/slot15_wrapper.v */
(* blackbox *)
module slot15_wrapper (
    inout wire vdd_3v3,
    inout wire vdd_1v2,
    inout wire vss_3v3,
    inout wire vss_1v2,
    input wire enable,
    input wire clk,
    input wire reset,
    input wire [23:0] dig_in,
    output wire [11:0] dig_out,
    inout wire analog_pin0,
    inout wire ibias0,
    inout wire ibias1,
    inout wire vbias,
    inout wire analog_bus0,
    inout wire analog_bus1,
    inout wire analog_bus2,
    inout wire analog_bus3
);
endmodule

/* slot16_wrapper --- 18 pins, from verilog/rtl/slot16_wrapper.v */
(* blackbox *)
module slot16_wrapper (
    inout wire vdd_3v3,
    inout wire vdd_1v2,
    inout wire vss_3v3,
    inout wire vss_1v2,
    input wire enable,
    input wire clk,
    input wire reset,
    input wire [23:0] dig_in,
    output wire [11:0] dig_out,
    inout wire analog_pin0,
    inout wire analog_pin1,
    inout wire ibias0,
    inout wire ibias1,
    inout wire vbias,
    inout wire analog_bus0,
    inout wire analog_bus1,
    inout wire analog_bus2,
    inout wire analog_bus3
);
endmodule

/* slot17_wrapper --- 18 pins, from verilog/rtl/slot17_wrapper.v */
(* blackbox *)
module slot17_wrapper (
    inout wire vdd_3v3,
    inout wire vdd_1v2,
    inout wire vss_3v3,
    inout wire vss_1v2,
    input wire enable,
    input wire clk,
    input wire reset,
    input wire [23:0] dig_in,
    output wire [11:0] dig_out,
    inout wire analog_pin0,
    inout wire analog_pin1,
    inout wire ibias0,
    inout wire ibias1,
    inout wire vbias,
    inout wire analog_bus0,
    inout wire analog_bus1,
    inout wire analog_bus2,
    inout wire analog_bus3
);
endmodule

/* slot18_wrapper --- 18 pins, from verilog/rtl/slot18_wrapper.v */
(* blackbox *)
module slot18_wrapper (
    inout wire vdd_3v3,
    inout wire vdd_1v2,
    inout wire vss_3v3,
    inout wire vss_1v2,
    input wire enable,
    input wire clk,
    input wire reset,
    input wire [23:0] dig_in,
    output wire [11:0] dig_out,
    inout wire analog_pin0,
    inout wire analog_pin1,
    inout wire ibias0,
    inout wire ibias1,
    inout wire vbias,
    inout wire analog_bus0,
    inout wire analog_bus1,
    inout wire analog_bus2,
    inout wire analog_bus3
);
endmodule

