// SPDX-FileCopyrightText: 2026 Open Circuit Design, LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// SPDX-License-Identifier: Apache-2.0

/*
 *-------------------------------------------------------------------------
 * chipalooza_frame_wrapper ---
 *
 * RTL verilog definition of the user project area for the open-frame
 * version of the Caravel harness chip, IHP SG13CMOS5L process, dual voltage
 * (1.2V core, 3.3V pad) padframe.
 *
 * Written by Tim Edwards
 * February 2026
 *
 * This file is automatically generated.  Do not edit.
 *-------------------------------------------------------------------------
 */

// `default_nettype none

// There are 44 GPIO pads in the openframe definition.  This
// is fixed and corresponds to the standard pinout and
// packaging for the Caravel harness chip.

`define OPENFRAME_IO_PADS 44

module chipalooza_frame_wrapper (
	`ifdef USE_POWER_PINS
		// Power buses
		inout  vddio,	// Core 5.0V supply
		inout  vssio,	// Core 5.0V ground
		inout  vccd,	// Core 3.3V supply
		inout  vssd,	// Core 3.3V ground
	`endif

	// Core infrastructure (padframe-facing pins)

	inout  s1_an_0_esd,
	inout  s1_an_0,
	inout  s1_an_1_esd,
	inout  s1_an_1,
	inout  s1_an_2_esd,
	inout  s1_an_2,
	inout  s1_an_3_esd,
	inout  s1_an_3,
	inout  s2_an_0_esd,
	inout  s2_an_0,
	inout  s3_an_0_esd,
	inout  s3_an_0,
	inout  s3_an_1_esd,
	inout  s3_an_1,
	inout  s4_an_0_esd,
	inout  s4_an_0,
	inout  s4_an_1_esd,
	inout  s4_an_1,
	inout  s4_an_2_esd,
	inout  s4_an_2,
	inout  s5_an_0_esd,
	inout  s5_an_0,
	inout  s5_an_1_esd,
	inout  s5_an_1,
	inout  s6_an_0_esd,
	inout  s6_an_0,
	inout  s7_an_0_esd,
	inout  s7_an_0,
	inout  s7_an_1_esd,
	inout  s7_an_1,
	inout  s8_an_0_esd,
	inout  s8_an_0,
	inout  s8_an_1_esd,
	inout  s8_an_1,
	inout  s8_an_2_esd,
	inout  s8_an_2,
	inout  s9_an_0_esd,
	inout  s9_an_0,
	inout  s9_an_1_esd,
	inout  s9_an_1,
	inout  s9_an_2_esd,
	inout  s9_an_2,
	inout  s10_an_0_esd,
	inout  s10_an_0,
	inout  s10_an_1_esd,
	inout  s10_an_1,
	inout  s11_an_0_esd,
	inout  s11_an_0,
	inout  s12_an_0_esd,
	inout  s12_an_0,
	inout  s12_an_1_esd,
	inout  s12_an_1,
	inout  s13_an_0_esd,
	inout  s13_an_0,
	inout  s13_an_1_esd,
	inout  s13_an_1,
	inout  s13_an_2_esd,
	inout  s13_an_2,
	inout  s14_an_0_esd,
	inout  s14_an_0,
	inout  s14_an_1_esd,
	inout  s14_an_1,
	inout  s15_an_0_esd,
	inout  s15_an_0,
	inout  s16_an_0_esd,
	inout  s16_an_0,
	inout  s16_an_1_esd,
	inout  s16_an_1,
	inout  s16_an_2_esd,
	inout  s16_an_2,
	inout  s16_an_3_esd,
	inout  s16_an_3,

	input  resetb_in,
	input  clock_in,
	input  option_in,
	input  [31:0] mask_rev
);

	// Declare a user project by defining HAS_USER_PROJECT
	// and specifying the "netlists.v" file to include the
	// RTL source code for it.

	`ifdef HAS_USER_PROJECT

	    /* The user is responsible for defining the user project
	     * instance and connecting the appropriate signals.  The
	     * user project itself is normally a schematic.
	     */

	`endif

endmodule
// `default_nettype wire
