#!/bin/env python3
#---------------------------------------------------------------
# parse_config.py ---
#
# Parse the "config.txt" file with information about what type
# of pad is at each GPIO pin position (for slots 1 to 18, with a
# varying number of pins per slot), and what core signal name to
# use at that position.  Using that information, make replacements
# into the following files to produce the given output files:
#
#	verilog/gl/:
#
#	chipalooza_frame_wrapper_template.v --> chipalooza_frame_wrapper.v
#	sg13cmos5l_padframe_template.v --> sg13cmos5l_padframe.v
#
#	scripts/:
#
#	gen_padframe_template.tcl --> gen_padframe.tcl
#
# If any of the output files (chipalooza_frame_wrapper.v,
# sg13cmos5l_padframe.v, or gen_padframe.tcl) exists, the flag an error
# and halt immediately.
#
# This script is specific to foundry process IHP SG13CMOS5L.
#
#---------------------------------------------------------------

import os
import sys
import re

# All files can be found relative to the location of this script.

script_file = os.path.realpath(__file__)
script_path = os.path.split(script_file)[0]
project_path = os.path.split(script_path)[0]
verilog_path = os.path.join(project_path, 'verilog')
verilog_gl_path = os.path.join(verilog_path, 'gl')

# Read the "config.txt" file from the project root directory

config_file = os.path.join(project_path, 'config.txt')
tcl_in_file = os.path.join(script_path, 'gen_padframe_template.tcl')
tcl_out_file = os.path.join(script_path, 'gen_padframe.tcl')
padframe_in_file = os.path.join(script_path, 'sg13cmos5l_padframe_template.v')
padframe_out_file = os.path.join(verilog_gl_path, 'sg13cmos5l_padframe.v')
wrapper_in_file = os.path.join(script_path, 'chipalooza_frame_wrapper_template.v')
wrapper_out_file = os.path.join(verilog_gl_path, 'chipalooza_frame_wrapper.v')

if not os.path.exists(config_file):
    print('Error:  Configuration file "config.txt" not found in project root directory.')
    print('        Expected project path is: ' + project_path)
    print('        Nothing to do, so quitting.')
    sys.exit(1)

if os.path.exists(tcl_out_file):
    print('Error:  Tcl script scripts/gen_padframe.tcl exists.')
    # print('        File is: ' + tcl_out_file)
    print('        Remove it or rename it before running this script.')
    sys.exit(1)

if os.path.exists(padframe_out_file):
    print('Error:  Padframe netlist verilog/gl/sg13cmos5l_padframe.v exists.')
    # print('        File is: ' + padframe_out_file)
    print('        Remove it or rename it before running this script.')
    sys.exit(1)

if os.path.exists(wrapper_out_file):
    print('Error:  Project wrapper netlist verilog/gl/chipalooza_frame_wrapper.v exists.')
    # print('        File is: ' + wrapper_out_file)
    print('        Remove it or rename it before running this script.')
    sys.exit(1)

idxrex = re.compile(r'^s([0-9]+)_an\[([0-9]+)\]:[ \t]+([^ \t]+)[ \t]+([^ \t]+)$')

# Create a dictionary of pad types and signal names, indexed by tuple of slot
# and pin number
padlist = {}

with open(config_file, 'r') as ifile:
    clines = ifile.read().splitlines()
    for line in clines:
        imatch = re.match(idxrex, line)
        if imatch:
            slot_index = imatch.group(1)
            pin_index = imatch.group(2)
            pad_type = imatch.group(3)
            signal_name = imatch.group(4)
            padlist[slot_index, pin_index] = [pad_type, signal_name]

#-----------------------------------------------------------------
# Prepare the chipalooza_frame_wrapper.v netlist
#-----------------------------------------------------------------

sprex = re.compile(r'^([ \t]*)[^ \t]')

wrapper_lines = []
wrapper_message = 'This file is automatically generated.  Do not edit.'
with open(wrapper_in_file, 'r') as ifile:
    wlines = ifile.read().splitlines()
    for line in wlines:
        if 'TEMPLATE_MESSAGE' in line:
            newline = re.sub('TEMPLATE_MESSAGE', wrapper_message, line)
            wrapper_lines.append(newline)
        elif 'INPUT_OUTPUT_LIST' in line:
            smatch = re.match(sprex, line)
            spaces = smatch.group(1)
            for pad_idx in padlist.keys():
                entry = padlist[pad_idx]
                pad_type = entry[0]
                signal_name = entry[1]
                if pad_type == 'sg13cmos5l_IOPadIn':
                    # The input pad has only one core facing signal
                    newline = spaces + 'input  ' + signal_name + ','
                elif pad_type == 'sg13cmos5l_IOPadAnalog':
                    # The input pad has the core signal + an ESD-protected signal
                    newline = spaces + 'inout  ' + signal_name + '_esd,'
                    wrapper_lines.append(newline)
                    newline = spaces + 'inout  ' + signal_name + ','
                elif pad_type.startswith('sg13cmos5l_IOPadOut'):
                    # The output-only pads have only one core facing signal
                    newline = spaces + 'output ' + signal_name + ','
                elif pad_type.startswith('sg13cmos5l_IOPadTriOut'):
                    # The output tristate pads have a core facing signal and enable
                    newline = spaces + 'output ' + signal_name + ','
                    wrapper_lines.append(newline)
                    newline = spaces + 'output ' + signal_name + '_ena,'
                    wrapper_lines.append(newline)
                    newline = spaces + 'input  ' + signal_name + '_one,'
                    wrapper_lines.append(newline)
                    newline = spaces + 'input  ' + signal_name + '_zero,'
                elif pad_type.startswith('sg13cmos5l_IOPadInOut'):
                    # The bidirectionsl pads have five core facing signals:  in,
                    # out, enable, and digital one and zero
                    newline = spaces + 'input  ' + signal_name + '_in,'
                    wrapper_lines.append(newline)
                    newline = spaces + 'output ' + signal_name + '_out,'
                    wrapper_lines.append(newline)
                    newline = spaces + 'output ' + signal_name + '_ena,'
                    wrapper_lines.append(newline)
                    newline = spaces + 'input  ' + signal_name + '_one,'
                    wrapper_lines.append(newline)
                    newline = spaces + 'input  ' + signal_name + '_zero,'
                else:
                    print('Error:  Bad pad type ' + pad_type)
                    newline = line
                wrapper_lines.append(newline)
        else:
            wrapper_lines.append(line)

with open(wrapper_out_file, 'w') as ofile:
    for line in wrapper_lines:
        print(line, file=ofile)

print('Done with generating project wrapper verilog netlist')

#--------------------------------------------------
# Prepare the sg13cmos5l_padframe.v netlist
#--------------------------------------------------

padrex = re.compile(r'[ \t]*PAD_([0-9]+)_([0-9]+)_([A-Z]+)[ \t]*')

padframe_lines = []
padframe_message = '/* This file is automatically generated.  Do not edit. */'
with open(padframe_in_file, 'r') as ifile:
    plines = ifile.read().splitlines()
    for line in plines:
        if 'TEMPLATE_MESSAGE' in line:
            newline = re.sub('TEMPLATE_MESSAGE', padframe_message, line)
            padframe_lines.append(newline)
        elif 'PAD_' in line:
            pmatch = re.search(padrex, line)
            if not pmatch:
                print('Error: could not parse line "' + line + '"')
                continue
            pad_slot_idx = pmatch.group(1)
            pad_pin_idx = pmatch.group(2)
            pad_subs = pmatch.group(3)
            padrec = padlist[pad_slot_idx, pad_pin_idx]
            subtext = 'PAD_' + pad_slot_idx + '_' + pad_pin_idx + '_' + pad_subs
            pad_type = padrec[0]
            if pad_subs == 'TYPE':
                # Pad type is a simple string substitution
                newline = re.sub(subtext, pad_type, line)
            elif pad_subs == 'SIGNALS':
                signal_name = padrec[1]
                smatch = re.match(sprex, line)
                spaces = smatch.group(1)
                # The pad signals depend on the pad type
                if pad_type == 'sg13cmos5l_IOPadIn':
                    newline = spaces + '.p2c(' + signal_name + ')'
                elif pad_type == 'sg13cmos5l_IOPadAnalog':
                    newline = spaces + '.padres(' + signal_name + '_esd)'
                elif pad_type.startswith('sg13cmos5l_IOPadOut'):
                    newline = spaces + '.c2p(' + signal_name + ')'
                elif pad_type.startswith('sg13cmos5l_IOPadTriOut'):
                    newline = spaces + '.c2p(' + signal_name + '),'
                    padframe_lines.append(newline)
                    newline = spaces + '.c2p_en(' + signal_name + '_ena)'
                elif pad_type.startswith('sg13cmos5l_IOPadInOut'):
                    newline = spaces + '.c2p(' + signal_name + '_out),'
                    padframe_lines.append(newline)
                    newline = spaces + '.c2p_en(' + signal_name + '_ena),'
                    padframe_lines.append(newline)
                    newline = spaces + '.p2c(' + signal_name + '_in)'
                else:
                    print('Bad pad type ' + pad_type)
                    newline = line
            else:
                newline = line
            padframe_lines.append(newline)

        elif 'INPUT_OUTPUT' in line:
            smatch = re.match(sprex, line)
            spaces = smatch.group(1)
            for pad_idx in padlist.keys():
                padrec = padlist[pad_idx]
                pad_type = padrec[0]
                signal_name = padrec[1]

                if pad_type == 'sg13cmos5l_IOPadIn':
                    newline = spaces + 'output wire ' + signal_name
                elif pad_type == 'sg13cmos5l_IOPadAnalog':
                    newline = spaces + 'inout wire ' + signal_name + '_esd,'
                elif pad_type.startswith('sg13cmos5l_IOPadOut'):
                    newline = spaces + 'input wire ' + signal_name + ','
                elif pad_type.startswith('sg13cmos5l_IOPadTriOut'):
                    newline = spaces + 'input wire ' + signal_name + ','
                    padframe_lines.append(newline)
                    newline = spaces + 'input wire ' + signal_name + '_ena,'
                elif pad_type.startswith('sg13cmos5l_IOPadInOut'):
                    newline = spaces + 'output wire ' + signal_name + '_in,'
                    padframe_lines.append(newline)
                    newline = spaces + 'input wire ' + signal_name + '_out,'
                    padframe_lines.append(newline)
                    newline = spaces + 'input wire ' + signal_name + '_ena,'
                    padframe_lines.append(newline)
                    newline = spaces + 'output wire ' + signal_name + '_one,'
                    padframe_lines.append(newline)
                    newline = spaces + 'output wire ' + signal_name + '_zero,'
                else:
                    print('Bad pad type ' + pad_type)
                    newline = line
                padframe_lines.append(newline)

        elif 'CONSTANT_BLOCKS' in line:
            smatch = re.match(sprex, line)
            spaces = smatch.group(1)
            for pad_idx in padlist.keys():
                padrec = padlist[pad_idx]
                pad_type = padrec[0]
                signal_name = padrec[1]
                if 'IOPadTriOut' in pad_type or 'IOPadInOut' in pad_type:
                    newline = spaces + 'constant_block constant_block_' + signal_name + ' ('
                    padframe_lines.append(newline)
                    newline = spaces + r'    `ifdef USE_POWER_PINS'
                    padframe_lines.append(newline)
                    newline = spaces + r'	.vdd(vccd),'
                    padframe_lines.append(newline)
                    newline = spaces + r'	.vss(vssd),'
                    padframe_lines.append(newline)
                    newline = spaces + r'    `endif  /* USE_POWER_PINS */'
                    padframe_lines.append(newline)
                    newline = spaces + r'    .one(' + signal_name + '_one),'
                    padframe_lines.append(newline)
                    newline = spaces + r'    .zero(' + signal_name + '_zero)'
                    padframe_lines.append(newline)
                    newline = spaces + r');'
                    padframe_lines.append(newline)

        else:
            padframe_lines.append(line)

with open(padframe_out_file, 'w') as ofile:
    for line in padframe_lines:
        print(line, file=ofile)

print('Done with generating padframe verilog netlist')

#--------------------------------------------------
# Prepare the gen_padframe.tcl file
#--------------------------------------------------

tcl_lines = []
tcl_message = 'This file is automatically generated.  Do not edit'
with open(tcl_in_file, 'r') as ifile:
    tlines = ifile.read().splitlines()
    for line in tlines:
        if 'TEMPLATE_MESSAGE' in line:
            newline = re.sub('TEMPLATE_MESSAGE', tcl_message, line)
            tcl_lines.append(newline)
        elif 'PAD_' in line:
            pmatch = re.search(padrex, line)
            if not pmatch:
                print('Error: could not parse line "' + line + '"')
                continue
            pad_slot_idx = pmatch.group(1)
            pad_pin_idx = pmatch.group(2)
            pad_subs = pmatch.group(3)
            try:
                padrec = padlist[pad_slot_idx, pad_pin_idx]
            except:
                print('Error:  slot ' + str(pad_slot_idx) + ' pin ' + str(pad_pin_idx) + ' not found in ' + tcl_in_file)
                sys.exit(1)
            subtext = 'PAD_' + pad_slot_idx + '_' + pad_pin_idx + '_' + pad_subs
            pad_type = padrec[0]
            if pad_subs == 'TYPE':
                # Pad type is a simple string substitution
                newline = re.sub(subtext, pad_type, line)
            elif pad_subs == 'SIGNALS':
                signal_name = padrec[1]
                smatch = re.match(sprex, line)
                spaces = smatch.group(1)
                # The slot index dictates what side of the chip the pad is on
                slot_num = int(pad_slot_idx)
                if slot_num >= 0 and slot_num <= 8:
                    side = 'right'
                else:
                    side = 'left'

                # The pad signals depend on the pad type
                if pad_type == 'sg13cmos5l_IOPadIn':
                    newline = spaces + 'label_' + side + '_signal pad_s' + pad_slot_idx + '_an_' + pad_pin_idx + '  p2c    ' + signal_name
                elif pad_type == 'sg13cmos5l_IOPadAnalog':
                    newline = spaces + 'label_' + side + '_signal pad_s' + pad_slot_idx + '_an_' + pad_pin_idx + '  padres    ' + signal_name + '_esd'
                    tcl_lines.append(newline)
                    # Note that in the padframe, since the analog core signal is
                    # connected directly to the pad, it has the name of the pad,
                    # not the given signal name.  The given signal name is used
                    # in the project wrapper.
                    newline = spaces + 'label_' + side + '_analog pad_s' + pad_slot_idx + '_an_' + pad_pin_idx + '  pad s' + pad_slot_idx + r'_an\[' + pad_pin_idx + r'\]'

                elif pad_type.startswith('sg13cmos5l_IOPadOut'):
                    newline = spaces + 'label_' + side + '_signal pad_s' + pad_slot_idx + '_an_' + pad_pin_idx + '  c2p    ' + signal_name
                elif pad_type.startswith('sg13cmos5l_IOPadTriOut'):
                    newline = spaces + 'label_' + side + '_signal pad_s' + pad_slot_idx + '_an_' + pad_pin_idx + '  c2p    ' + signal_name
                    tcl_lines.append(newline)
                    newline = spaces + 'label_' + side + '_signal pad_s' + pad_slot_idx + '_an_' + pad_pin_idx + '  c2p_en ' + signal_name + '_ena'

                elif pad_type.startswith('sg13cmos5l_IOPadInOut'):
                    newline = spaces + 'label_' + side + '_signal pad_s' + pad_slot_idx + '_an_' + pad_pin_idx + '  c2p    ' + signal_name + '_out'
                    tcl_lines.append(newline)
                    newline = spaces + 'label_' + side + '_signal pad_s' + pad_slot_idx + '_an_' + pad_pin_idx + '  c2p_en ' + signal_name + '_ena'
                    tcl_lines.append(newline)
                    newline = spaces + 'label_' + side + '_signal pad_s' + pad_slot_idx + '_an_' + pad_pin_idx + '  p2c    ' + signal_name + '_in'

            tcl_lines.append(newline)

        elif 'CONSTANT_BLOCKS' in line:
            smatch = re.match(sprex, line)
            spaces = smatch.group(1)
            for pad_idx in padlist.keys():
                padrec = padlist[pad_idx]
                pad_slot_idx = pad_idx[0]
                pad_pin_idx = pad_idx[1]
                pad_type = padrec[0]
                signal_name = padrec[1]
                if 'IOPadTriOut' in pad_type or 'IOPadInOut' in pad_type:
                    slot_num = int(pad_slot_idx)
                    if pad_num >= 0 and pad_num <= 8:
                        side = 'right'
                    else:
                        side = 'left'
                    newline = spaces + 'add_constant_' + side + ' pad_s' + pad_slot_idx + '_an_' + pad_pin_idx + ' const_' + pad_pin_idx
                    tcl_lines.append(newline)

        elif 'CONSTANT_SIGNALS' in line:
            smatch = re.match(sprex, line)
            spaces = smatch.group(1)
            for pad_idx in padlist.keys():
                padrec = padlist[pad_idx]
                pad_slot_idx = pad_idx[0]
                pad_pin_idx = pad_idx[1]
                pad_type = padrec[0]
                signal_name = padrec[1]
                if 'IOPadTriOut' in pad_type or 'IOPadInOut' in pad_type:
                    slot_num = int(pad_slot_idx)
                    if pad_num >= 0 and pad_num <= 8:
                        side = 'right'
                    else:
                        side = 'left'
                    newline = spaces + 'label_' + side + '_signal const_' + pad_slot_idx + '_' + pad_pin_idx + '    zero ' + signal_name + '_zero'
                    tcl_lines.append(newline)
                    newline = spaces + 'label_' + side + '_signal const_' + pad_slot_idx + '_' + pad_pin_idx + '    one ' + signal_name + '_one'
                    tcl_lines.append(newline)
        else:
            tcl_lines.append(line)

with open(tcl_out_file, 'w') as ofile:
    for line in tcl_lines:
        print(line, file=ofile)

print('Done with generating layout Tcl script')

print('Done with generating all files')

sys.exit(0)
