#!/bin/bash
#
# Run layout GDS generation on sg13cmos5l_caravel_openframe
# Run this script from the magic/ directory
#
# This is a compositor designed to do the following:
# (1) Read the project wrapper GDS in "readonly" mode
# (2) Read the seal ring
# (3) Read the padframe
# (4) Place the user project wrapper
# (5) Write the top level .mag file
# (6) Write final GDS with no hierarchical processing
#
# Not done (yet)---Set the user ID
#
echo ${PDK_ROOT:=/home/tim/gits} > /dev/null
echo ${PDK:=ihp-sg13cmos5l} > /dev/null

echo "Generating GDS for sg13cmos5l_caravel_openframe"

# Remove any existing top-level layout.  The top level is automatically
# generated by this script, so deleting it should not be an issue.
rm -f sg13cmos5l_caravel_openframe.mag

magic -dnull -noconsole -rcfile ${PDK_ROOT}/${PDK}/libs.tech/magic/${PDK}.magicrc << EOF
drc off
crashbackups stop
locking disable

gds readonly true
gds rescale false
gds read ../gds/chipalooza_frame_wrapper.gds.gz

units microns
snap internal

addpath sealring
load sg13cmos5l_caravel_openframe -silent

box values 0 0 0 0
getcell sealring_complete child 0 0
box position 16.1 16.1
getcell sg13cmos5l_padframe child 0 0
box position 16.1 16.1
getcell chipalooza_frame_wrapper child 0 0

# Flatten the top-level pad pin cell into the layout
box position 16.1 16.1
dump padframe_pins child 0 0

# The top level layout is only used for top-level LVS.
writeall force sg13cmos5l_caravel_openframe

cif *hier write disable
gds compress 9
gds write sg13cmos5l_caravel_openframe
quit -noprompt
EOF
mv sg13cmos5l_caravel_openframe.gds.gz ../gds/
echo "Done!"
exit 0
